development:
  adapter: postgresql
  database: buycoins_dev
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  user: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: buycoins_test
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
